# Generated by Django 5.0.6 on 2024-06-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "check_in_time",
                    models.TimeField(
                        auto_now_add=True, null=True, verbose_name="check_in_time"
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        auto_now=True, null=True, verbose_name="check_out_time"
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="age")),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="gender"
                    ),
                ),
                (
                    "table_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.table",
                        verbose_name="table_id",
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
