# Generated by Django 3.2.19 on 2024-07-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240618_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stay_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='stay_time'),
        ),
    ]
