# Generated by Django 3.2.19 on 2024-07-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_stay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='check_out_time'),
        ),
    ]
