# Generated by Django 3.2.19 on 2024-07-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customer_check_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='stay_time',
            field=models.TimeField(blank=True, null=True, verbose_name='stay_time'),
        ),
    ]
