# Generated by Django 5.0.6 on 2024-06-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_seats",
                    models.IntegerField(
                        max_length=2, unique=True, verbose_name="max_seats"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=50, unique=True, verbose_name="status"),
                ),
            ],
            options={
                "db_table": "table",
            },
        ),
    ]
