# Generated by Django 5.0.6 on 2024-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="max_seats",
            field=models.IntegerField(max_length=2, verbose_name="max_seats"),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(max_length=50, verbose_name="status"),
        ),
    ]
